import React, { useEffect, useState } from 'react';
import { Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { AnalyseResult, verifyAssessment } from '@/services/api';
import { useAuth } from '@/context/AuthContext';
import * as ImagePicker from 'expo-image-picker';

const CHECKS=['Leaking','Movement','Heat','Odour','Sparking','Smoke','Swelling','Worsening damage','Newly exposed material','Water near electrical fittings'];
export default function Guided(){const params=useLocalSearchParams<{result:string}>();const router=useRouter();const{token}=useAuth();const[result,setResult]=useState<AnalyseResult|null>(null);const[index,setIndex]=useState(0);const[checked,setChecked]=useState(false);const[changes,setChanges]=useState<Record<string,boolean>>({});const[paused,setPaused]=useState(false);const[completed,setCompleted]=useState(false);const[afterPhoto,setAfterPhoto]=useState(false);
useEffect(()=>{const raw=params.result; if(!raw||!token)return;try{const parsed=JSON.parse(raw);verifyAssessment(parsed,token).then(async safe=>{setResult(safe);const saved=await AsyncStorage.getItem(key(safe));setIndex(Math.min(Number(saved||0),Math.max(0,safe.steps.length-1)))}).catch(e=>Alert.alert('Guided repair locked',e.message))}catch{Alert.alert('Guided repair locked','Invalid repair state.')}},[params.result,token]);
async function next(value:number){if(!result)return;try{await AsyncStorage.setItem(key(result),String(value));setIndex(value)}catch{Alert.alert('Progress not saved','Keep this screen open or try again.')}}
async function confirm(){if(!result||!token)return;const escalated=Object.values(changes).some(Boolean);if(escalated){const safe=await verifyAssessment(result,token,changes);setResult(safe);if(!allowed(safe)){Alert.alert('Repair locked',safe.diy_assessment?.reason||'A professional assessment is required.');return}}setChecked(true)}
if(!result)return <SafeAreaView style={s.safe}><Text style={s.title}>Verifying backend assessment…</Text></SafeAreaView>;if(!allowed(result))return <SafeAreaView style={s.safe}><Text style={s.title}>Guided repair is locked</Text><Text style={s.body}>{result.diy_assessment?.reason}</Text></SafeAreaView>;if(!checked)return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Has anything changed?</Text>{CHECKS.map(item=><TouchableOpacity key={item} style={[s.check,changes[item]&&s.selected]} onPress={()=>setChanges(v=>({...v,[item]:!v[item]}))}><Text style={s.body}>{changes[item]?'✓ ':'○ '}{item}</Text></TouchableOpacity>)}<TouchableOpacity style={s.primary} onPress={confirm}><Text style={s.primaryText}>Continue safety check</Text></TouchableOpacity></ScrollView></SafeAreaView>;
if(completed)return <SafeAreaView style={s.safe}><View style={s.content}><Text style={s.title}>Did this fix the problem?</Text><TouchableOpacity style={s.secondary} onPress={async()=>{const photo=await ImagePicker.launchCameraAsync({quality:.8});setAfterPhoto(!photo.canceled)}}><Text>{afterPhoto?'✓ After photo added':'Add after photo'}</Text></TouchableOpacity><View style={s.row}>{['Yes','Partly','No'].map(answer=><TouchableOpacity key={answer} disabled={!afterPhoto} style={s.primarySmall} onPress={()=>answer==='Yes'?router.replace('/(tabs)/repairs'):router.replace('/(tabs)/chat')}><Text style={s.primaryText}>{answer}</Text></TouchableOpacity>)}</View></View></SafeAreaView>;
const step=result.steps[index];return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.progress}>STEP {index+1} OF {result.steps.length}</Text><TouchableOpacity onPress={()=>setPaused(!paused)}><Text style={s.link}>{paused?'Resume':'Pause'}</Text></TouchableOpacity>{paused?<Text style={s.title}>Repair paused</Text>:<View style={s.card}><Text style={s.title}>{step.title}</Text><Text style={s.body}>{step.description}</Text><Text style={s.body}>{step.duration_minutes} minutes</Text><View style={s.row}><TouchableOpacity disabled={index===0} style={s.secondary} onPress={()=>next(index-1)}><Text>Previous</Text></TouchableOpacity><TouchableOpacity style={s.primarySmall} onPress={()=>index<result.steps.length-1?next(index+1):setCompleted(true)}><Text style={s.primaryText}>Done</Text></TouchableOpacity></View><TouchableOpacity onPress={()=>router.push('/(tabs)/chat')}><Text style={s.link}>I need help</Text></TouchableOpacity></View>}<TouchableOpacity style={s.stop} onPress={()=>setChecked(false)}><Text style={s.stopText}>Stop—something changed</Text></TouchableOpacity></ScrollView></SafeAreaView>}
const allowed=(r:AnalyseResult)=>r.diy_assessment?.assessment_status==='complete'&&[1,2].includes(r.diy_assessment.safety_level||0)&&!r.requires_reassessment&&r.steps.length>0;const key=(r:AnalyseResult)=>`taskai:guided:${r.diy_assessment?.validation_version||'unknown'}:${r.diy_assessment?.assessed_at||'unknown'}`;
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F7F3E9'},content:{padding:20,paddingBottom:50},title:{fontSize:28,fontWeight:'900',color:'#102F36',marginVertical:14},body:{fontSize:16,lineHeight:25,color:'#52676A'},progress:{fontSize:12,fontWeight:'900',letterSpacing:2,color:'#B95320'},check:{minHeight:48,justifyContent:'center',padding:12,marginBottom:8,borderRadius:12,borderWidth:1,borderColor:'#C9C1AE',backgroundColor:'#FFF'},selected:{backgroundColor:'#EAF0DF'},card:{backgroundColor:'#FFF',padding:22,borderRadius:20,marginTop:12},primary:{minHeight:50,alignItems:'center',justifyContent:'center',backgroundColor:'#0D3339',borderRadius:13,marginTop:14},primarySmall:{flex:1,minHeight:48,alignItems:'center',justifyContent:'center',backgroundColor:'#0D3339',borderRadius:12},primaryText:{color:'#FFF',fontWeight:'800'},secondary:{flex:1,minHeight:48,alignItems:'center',justifyContent:'center',borderWidth:1,borderRadius:12},row:{flexDirection:'row',gap:10,marginTop:22},link:{minHeight:44,paddingVertical:12,color:'#B95320',fontWeight:'800',textAlign:'center'},stop:{minHeight:50,alignItems:'center',justifyContent:'center',backgroundColor:'#991B1B',borderRadius:25,marginTop:24},stopText:{color:'#FFF',fontWeight:'900'}});
