import { useEffect, useMemo, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { apiFetch } from '../lib/api'
import { supabase } from '../lib/supabase'
import { CHANGE_CHECKS, applyProgress, canEnterGuided, progressKey, shouldEscalate } from '../lib/guidedRepair'

export default function GuidedRepair(){
  const {state}=useLocation();const navigate=useNavigate();const [result,setResult]=useState(null);const [loading,setLoading]=useState(true);const [index,setIndex]=useState(0);const [changes,setChanges]=useState({});const [checked,setChecked]=useState(false);const [paused,setPaused]=useState(false);const [saveError,setSaveError]=useState('');const [outcome,setOutcome]=useState(null);const [afterPhoto,setAfterPhoto]=useState(null)
  useEffect(()=>{verify(state?.result||null)},[])
  async function verify(candidate,changed={}){if(!candidate){setLoading(false);return}setLoading(true);try{const {data:{session}}=await supabase.auth.getSession();const safe=await apiFetch(`${import.meta.env.VITE_API_URL}/assessments/verify`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token}`},body:JSON.stringify({result:candidate,changed_conditions:changed})});setResult(safe);const saved=Number(localStorage.getItem(progressKey(safe))||0);setIndex(applyProgress(safe.steps?.length||0,saved))}catch(e){setSaveError(e.message||'Assessment verification failed')}finally{setLoading(false)}}
  const allowed=useMemo(()=>canEnterGuided(result,true),[result]);
  async function save(next){try{localStorage.setItem(progressKey(result),String(next));setIndex(next)}catch{setSaveError('Progress could not be saved on this device.')} }
  async function confirmChanges(){setChecked(true);if(shouldEscalate(changes))await verify(result,changes)}
  if(loading)return <State title="Verifying the backend safety assessment…"/>;if(!result||!allowed)return <State title="Guided repair is locked" body={saveError||result?.diy_assessment?.reason||'Open an eligible assessment to begin.'}/>;
  if(!checked)return <main className="mx-auto max-w-3xl p-4 sm:p-8"><h1 className="text-3xl font-black">Has anything changed?</h1><p className="mt-2 text-[#52676a]">Select every change since this repair was assessed.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{CHANGE_CHECKS.map(item=><label key={item} className="min-h-12 flex items-center gap-3 rounded-xl border bg-white p-3"><input type="checkbox" onChange={e=>setChanges(c=>({...c,[item.toLowerCase().replaceAll(' ','_')]:e.target.checked}))}/>{item}</label>)}</div><button onClick={confirmChanges} className="mt-6 min-h-12 w-full rounded-xl bg-[#0d3339] font-bold text-white">Continue safety check</button></main>;
  const step=result.steps[index];if(outcome)return <main className="mx-auto max-w-3xl p-6"><h1 className="text-3xl font-black">Repair check-in</h1><p className="mt-3">Outcome: {outcome}</p>{outcome!=='Yes'&&<button onClick={()=>navigate('/diagnose')} className="mt-5 min-h-12 rounded-xl bg-[#f28b45] px-5 font-bold">Open contextual chat</button>}</main>;
  return <main className="mx-auto max-w-3xl p-4 sm:p-8"><div className="sticky top-0 z-10 rounded-2xl bg-[#0d3339] p-4 text-white"><div className="flex justify-between"><strong>Step {index+1} of {result.steps.length}</strong><button onClick={()=>setPaused(!paused)}>{paused?'Resume':'Pause'}</button></div><div className="mt-2 h-2 rounded bg-white/20"><div className="h-full rounded bg-[#f28b45]" style={{width:`${((index+1)/result.steps.length)*100}%`}}/></div></div>{paused?<State title="Repair paused" body="Your completed progress is preserved."/>:<section className="mt-6 rounded-3xl bg-white p-6"><p className="text-sm font-bold uppercase text-[#b95320]">{step.phase}</p><h1 className="mt-2 text-3xl font-black">{step.title}</h1><p className="mt-5 text-lg leading-8">{step.description}</p><p className="mt-4 font-bold">About {step.duration_minutes} minutes</p><button onClick={()=>speechSynthesis.speak(new SpeechSynthesisUtterance(`${step.title}. ${step.description}`))} className="mt-4 min-h-11 rounded-xl border px-4">Read aloud</button><div className="mt-6 grid grid-cols-2 gap-3"><button disabled={index===0} onClick={()=>save(index-1)} className="min-h-12 rounded-xl border disabled:opacity-40">Previous</button><button onClick={()=>index===result.steps.length-1?setOutcome('Pending'):save(index+1)} className="min-h-12 rounded-xl bg-[#0d3339] font-bold text-white">Done</button></div><button onClick={()=>navigate('/diagnose')} className="mt-3 min-h-11 w-full underline">I need help</button></section>}<button onClick={()=>{setChecked(false);setChanges({})}} className="fixed bottom-24 right-4 min-h-12 rounded-full bg-red-700 px-5 font-black text-white shadow-xl">Stop—something changed</button>{index===result.steps.length-1&&<section className="mt-6 rounded-2xl bg-white p-5"><label className="font-bold">After photo<input type="file" accept="image/*" className="mt-2 block" onChange={e=>setAfterPhoto(e.target.files?.[0]||null)}/></label><p className="mt-4 font-bold">Did this fix the problem?</p><div className="mt-2 flex gap-2">{['Yes','Partly','No'].map(x=><button key={x} disabled={!afterPhoto} onClick={()=>setOutcome(x)} className="min-h-11 flex-1 rounded-xl border disabled:opacity-40">{x}</button>)}</div></section>}{saveError&&<p role="alert" className="mt-4 text-red-700">{saveError}</p>}</main>
}
function State({title,body}){return <main className="mx-auto max-w-2xl p-8"><h1 className="text-3xl font-black">{title}</h1>{body&&<p className="mt-3 text-[#52676a]">{body}</p>}</main>}
