import { Link } from 'react-router-dom'

export default function Landing(){return <div className="min-h-dvh overflow-x-hidden bg-[#f7f3e9] text-[#102f36]">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-8"><Link to="/" className="text-2xl font-black">task<span className="text-[#f28b45]">.ai</span></Link><nav aria-label="Account" className="flex items-center gap-2"><a href="#how" className="hidden min-h-11 items-center px-3 font-bold sm:flex">See how it works</a><Link to="/login" className="flex min-h-11 items-center rounded-xl border border-[#0d3339] px-4 font-bold">Log in</Link></nav></header>
  <main><section className="mx-auto grid max-w-7xl items-center gap-10 px-4 py-14 sm:px-8 lg:grid-cols-2 lg:py-24"><div><p className="text-sm font-black uppercase tracking-[.22em] text-[#b95320]">Australian home repair guidance</p><h1 className="mt-4 text-5xl font-black leading-[1.02] sm:text-6xl">Not sure how to fix it? Take a photo.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#52676a]">Task AI helps identify visible repair issues, checks DIY eligibility for your selected Australian jurisdiction, and guides you toward a safer next step.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/login" className="flex min-h-12 items-center rounded-xl bg-[#f28b45] px-6 font-black">Diagnose a repair</Link><a href="#how" className="flex min-h-12 items-center rounded-xl border border-[#0d3339] px-6 font-black">See how it works</a></div><p className="mt-5 text-xs leading-5 text-[#607176]">Task AI provides general information. It does not guarantee safety, certify legality, replace a qualified professional, or reliably identify every hidden hazard from an image.</p></div><div aria-label="Illustrative before and after repair" className="rounded-[2rem] bg-[#0d3339] p-5 shadow-2xl"><div className="grid grid-cols-2 gap-3"><Visual label="Before" damaged/><Visual label="Illustrative after"/></div><p className="mt-4 text-center text-xs text-[#c6d6d1]">Illustration only — actual outcomes vary</p></div></section>
  <section id="how" className="bg-[#0d3339] px-4 py-16 text-white sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-sm font-black uppercase tracking-[.22em] text-[#f2a66e]">How it works</p><div className="mt-8 grid gap-4 md:grid-cols-3">{[['1','Photograph the problem','Use a clear photo of the affected area without approaching immediate hazards.'],['2','Check DIY eligibility','The backend checks hazards, your jurisdiction and verified policy status.'],['3','Repair safely or contact a professional','Follow eligible guidance, or stop and use the recommended professional or emergency pathway.']].map(([n,t,d])=><article key={n} className="rounded-2xl border border-white/10 bg-white/5 p-6"><span className="grid h-10 w-10 place-items-center rounded-full bg-[#f28b45] font-black text-[#102f36]">{n}</span><h2 className="mt-5 text-xl font-black">{t}</h2><p className="mt-2 leading-7 text-[#c6d6d1]">{d}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-6xl gap-6 px-4 py-16 sm:px-8 md:grid-cols-3"><Info title="Australian context">Jurisdiction-aware assessments, AUD estimates and links to familiar Australian retailers. Victoria is currently the only verified policy jurisdiction.</Info><Info title="Privacy by design">We use your selected state or territory—not a precise address. Your saved repairs remain private to your authenticated account.</Info><Info title="Know the limits">Images cannot reveal every concealed service, structural issue or hazardous material. Stop conditions always take priority.</Info></section></main>
  <footer className="border-t border-[#ddd5c3] px-4 py-8 text-center text-sm text-[#607176]">Task AI · General information only · Australia</footer>
</div>}
function Visual({label,damaged=false}){return <div><div className={`relative aspect-[4/5] overflow-hidden rounded-2xl ${damaged?'bg-[#cdb69f]':'bg-[#dce8d5]'}`}><div className="absolute inset-x-4 bottom-5 h-2 rounded bg-[#8d745f]"/>{damaged&&<div className="absolute left-1/2 top-1/4 h-1/2 w-1 -rotate-12 bg-[#5c4637]"/>}{!damaged&&<div className="absolute inset-x-8 top-1/3 h-12 rounded-full bg-white/40"/>}</div><p className="mt-2 text-center text-xs font-bold text-white">{label}</p></div>}
function Info({title,children}){return <article className="rounded-2xl border border-[#ddd5c3] bg-[#fffdf7] p-6"><h2 className="text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-[#52676a]">{children}</p></article>}
